spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

rdcw.api.clientId=${RDCW_CLIENT_ID}
rdcw.api.clientSecret=${RDCW_CLIENT_SECRET}
rdcw.api.expectedReceiverName=${RDCW_RECEIVER_NAME}

nanobanana.api.url=https://vbycspuzwyhzkfdodopt.supabase.co/functions/v1/nanobanana-api?action=generate
nanobanana.api.key=${NANOBANANA_API_KEY}

openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.key=${OPENROUTER_API_KEY}

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.success.url=${STRIPE_SUCCESS_URL}
stripe.cancel.url=${STRIPE_CANCEL_URL}

allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000}
